# TODO: fill in GCP connection config
default_environment: default
environments:
  default:
    connections:
      google_cloud_platform:
        - name: "gcp-default"
          project_id: ""
          service_account_file: ""
          location: "australia-southeast1"
